# Generated by Django 3.2.3 on 2021-05-16 09:57
# Add the test data

from django.db import migrations

from route_api.models import Routes


def add_nodes(apps, schema_editor):
    node_data = [(1,2), (1,6), (2,3), (2,6), (3,4), (4,5), (4,6)]
    for this_node in node_data:
        new_node = Routes(node_a=this_node[0], node_b=this_node[1])
        new_node.save()

class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_nodes),
    ]
